// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/decision_trees/proto/generic_tree_model_extensions.proto

#ifndef PROTOBUF_tensorflow_2fcontrib_2fdecision_5ftrees_2fproto_2fgeneric_5ftree_5fmodel_5fextensions_2eproto__INCLUDED
#define PROTOBUF_tensorflow_2fcontrib_2fdecision_5ftrees_2fproto_2fgeneric_5ftree_5fmodel_5fextensions_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3004000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow/contrib/decision_trees/proto/generic_tree_model.pb.h"
// @@protoc_insertion_point(includes)
namespace tensorflow {
namespace decision_trees {
class MatchingValuesTest;
class MatchingValuesTestDefaultTypeInternal;
extern MatchingValuesTestDefaultTypeInternal _MatchingValuesTest_default_instance_;
}  // namespace decision_trees
}  // namespace tensorflow

namespace tensorflow {
namespace decision_trees {

namespace protobuf_tensorflow_2fcontrib_2fdecision_5ftrees_2fproto_2fgeneric_5ftree_5fmodel_5fextensions_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static void InitDefaultsImpl();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_tensorflow_2fcontrib_2fdecision_5ftrees_2fproto_2fgeneric_5ftree_5fmodel_5fextensions_2eproto

// ===================================================================

class MatchingValuesTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.decision_trees.MatchingValuesTest) */ {
 public:
  MatchingValuesTest();
  virtual ~MatchingValuesTest();

  MatchingValuesTest(const MatchingValuesTest& from);

  inline MatchingValuesTest& operator=(const MatchingValuesTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MatchingValuesTest(MatchingValuesTest&& from) noexcept
    : MatchingValuesTest() {
    *this = ::std::move(from);
  }

  inline MatchingValuesTest& operator=(MatchingValuesTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MatchingValuesTest& default_instance();

  static inline const MatchingValuesTest* internal_default_instance() {
    return reinterpret_cast<const MatchingValuesTest*>(
               &_MatchingValuesTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MatchingValuesTest* other);
  friend void swap(MatchingValuesTest& a, MatchingValuesTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MatchingValuesTest* New() const PROTOBUF_FINAL { return New(NULL); }

  MatchingValuesTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MatchingValuesTest& from);
  void MergeFrom(const MatchingValuesTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MatchingValuesTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.decision_trees.Value value = 2;
  int value_size() const;
  void clear_value();
  static const int kValueFieldNumber = 2;
  const ::tensorflow::decision_trees::Value& value(int index) const;
  ::tensorflow::decision_trees::Value* mutable_value(int index);
  ::tensorflow::decision_trees::Value* add_value();
  ::google::protobuf::RepeatedPtrField< ::tensorflow::decision_trees::Value >*
      mutable_value();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::decision_trees::Value >&
      value() const;

  // .tensorflow.decision_trees.FeatureId feature_id = 1;
  bool has_feature_id() const;
  void clear_feature_id();
  static const int kFeatureIdFieldNumber = 1;
  const ::tensorflow::decision_trees::FeatureId& feature_id() const;
  ::tensorflow::decision_trees::FeatureId* mutable_feature_id();
  ::tensorflow::decision_trees::FeatureId* release_feature_id();
  void set_allocated_feature_id(::tensorflow::decision_trees::FeatureId* feature_id);

  // bool inverse = 3;
  void clear_inverse();
  static const int kInverseFieldNumber = 3;
  bool inverse() const;
  void set_inverse(bool value);

  // @@protoc_insertion_point(class_scope:tensorflow.decision_trees.MatchingValuesTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::decision_trees::Value > value_;
  ::tensorflow::decision_trees::FeatureId* feature_id_;
  bool inverse_;
  mutable int _cached_size_;
  friend struct protobuf_tensorflow_2fcontrib_2fdecision_5ftrees_2fproto_2fgeneric_5ftree_5fmodel_5fextensions_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MatchingValuesTest

// .tensorflow.decision_trees.FeatureId feature_id = 1;
inline bool MatchingValuesTest::has_feature_id() const {
  return this != internal_default_instance() && feature_id_ != NULL;
}
inline void MatchingValuesTest::clear_feature_id() {
  if (GetArenaNoVirtual() == NULL && feature_id_ != NULL) delete feature_id_;
  feature_id_ = NULL;
}
inline const ::tensorflow::decision_trees::FeatureId& MatchingValuesTest::feature_id() const {
  const ::tensorflow::decision_trees::FeatureId* p = feature_id_;
  // @@protoc_insertion_point(field_get:tensorflow.decision_trees.MatchingValuesTest.feature_id)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::decision_trees::FeatureId*>(
      &::tensorflow::decision_trees::_FeatureId_default_instance_);
}
inline ::tensorflow::decision_trees::FeatureId* MatchingValuesTest::mutable_feature_id() {
  
  if (feature_id_ == NULL) {
    feature_id_ = new ::tensorflow::decision_trees::FeatureId;
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.decision_trees.MatchingValuesTest.feature_id)
  return feature_id_;
}
inline ::tensorflow::decision_trees::FeatureId* MatchingValuesTest::release_feature_id() {
  // @@protoc_insertion_point(field_release:tensorflow.decision_trees.MatchingValuesTest.feature_id)
  
  ::tensorflow::decision_trees::FeatureId* temp = feature_id_;
  feature_id_ = NULL;
  return temp;
}
inline void MatchingValuesTest::set_allocated_feature_id(::tensorflow::decision_trees::FeatureId* feature_id) {
  delete feature_id_;
  if (feature_id != NULL && feature_id->GetArena() != NULL) {
    ::tensorflow::decision_trees::FeatureId* new_feature_id = new ::tensorflow::decision_trees::FeatureId;
    new_feature_id->CopyFrom(*feature_id);
    feature_id = new_feature_id;
  }
  feature_id_ = feature_id;
  if (feature_id) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.decision_trees.MatchingValuesTest.feature_id)
}

// repeated .tensorflow.decision_trees.Value value = 2;
inline int MatchingValuesTest::value_size() const {
  return value_.size();
}
inline void MatchingValuesTest::clear_value() {
  value_.Clear();
}
inline const ::tensorflow::decision_trees::Value& MatchingValuesTest::value(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.decision_trees.MatchingValuesTest.value)
  return value_.Get(index);
}
inline ::tensorflow::decision_trees::Value* MatchingValuesTest::mutable_value(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.decision_trees.MatchingValuesTest.value)
  return value_.Mutable(index);
}
inline ::tensorflow::decision_trees::Value* MatchingValuesTest::add_value() {
  // @@protoc_insertion_point(field_add:tensorflow.decision_trees.MatchingValuesTest.value)
  return value_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::decision_trees::Value >*
MatchingValuesTest::mutable_value() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.decision_trees.MatchingValuesTest.value)
  return &value_;
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::decision_trees::Value >&
MatchingValuesTest::value() const {
  // @@protoc_insertion_point(field_list:tensorflow.decision_trees.MatchingValuesTest.value)
  return value_;
}

// bool inverse = 3;
inline void MatchingValuesTest::clear_inverse() {
  inverse_ = false;
}
inline bool MatchingValuesTest::inverse() const {
  // @@protoc_insertion_point(field_get:tensorflow.decision_trees.MatchingValuesTest.inverse)
  return inverse_;
}
inline void MatchingValuesTest::set_inverse(bool value) {
  
  inverse_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.decision_trees.MatchingValuesTest.inverse)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace decision_trees
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_2fcontrib_2fdecision_5ftrees_2fproto_2fgeneric_5ftree_5fmodel_5fextensions_2eproto__INCLUDED
